### PR TITLE
Add Dockerfile and Docker entrypoint with cron functionality

### PR DESCRIPTION
**Pull request by Skyr**
Create a Docker image which allows either execution of single commands, or running the container continuously, updating the phonebook in given intervals.

### CODE REVIEW

**Comment by andig** [comment]
Nice pr, thank you very much! Will add pre-built docker image to travis config, too.

**Comment by Skyr** [comment]
You're welcome - thank you for maintaining this cool tool!

**Comment by andig** [comment]
Still fighting with the travis `deploy` step syntax which seems to require a separate script the I'd like to avoid. Any hints welcome...

**Comment by Skyr** [comment]
When pushing, you need to specify the tag as well. So it should be `docker push ${TRAVIS_REPO_SLUG}:latest`

**Comment by andig** [comment]
See https://travis-ci.org/andig/carddav2fb/jobs/532194550:

	+docker push [secure]/carddav2fb:latestn
	The push refers to a repository [docker.io/[secure]/carddav2fb]
	tag does not exist: [secure]/carddav2fb:latestn
	
`latestn` -> problem seems to be the string handling of the `script` tag. I assume the `n` is an appended line break.

**Comment by molfi** [comment]
Hi @Skyr .

Contacting you on this pull request which was a nice idea!
The Docker container works like a charm on Synology NAS.

Would like to upload more than one phone book to the Fritzbox.
Its discussed basically here how to achieve that with carddav2fb (sorry, discussion in German)
[https://www.ip-phone-forum.de/threads/carddav-to-fritzbox-2-0-neue-version-verf%C3%BCgbar.298117/page-11#post-2357458](url)

When I want to do that in Docker I would need to create 1 container per phone book.
Is that correct?
Would it be an option to have a kind of loop in the "docker-entrypoint" to check for more than 1 "run"? 
What do you think?

**Pull request merged**
