### PR TITLE
PHOTO 3.0 URI fix

### LINKED ISSUE #170: Allow URI as data for vcard PHOTO
Nextcloud has implemented a change to allow URI as data for VCards: https://github.com/nextcloud/server/pull/13117
Consequently, I find in my database a number of VCFs 3.0 with:
`BEGIN:VCARD`
`VERSION:3.0`
`PRODID:-//Sabre//Sabre VObject 4.1.6//EN`
`UID:C7821D49-BED0-0001-7F2A-E8507C67107F.vcf`
`FN:xxxx`
`ORG:xxxx`
`PHOTO;VALUE=URI:DATA:IMAGE/JPEG;BASE64\,/9j/4QAYRXhpZgAASUkqAAgAAAAAAAAAAAA`

These photos are not recognized by carddav2fb und thus missing from the uploaded phonebook.

### PR DESCRIPTION
**Pull request by blacksenator**
Fix #170

### CODE REVIEW

**Comment by SpamReceiver** [comment]
> 
> 
> /cc @SpamReceiver could you test this?

Yes, I would like to, but how do I access the changed files? I'm quite unfamilar with GIT...

**Comment by andig** [comment]
See https://stackoverflow.com/questions/27567846/how-can-i-check-out-a-github-pull-request-with-git#30584951 for hints how to do this.

**Comment by SpamReceiver** [comment]
Tested successfully: git pull origin pull/172/head

./carddav2fb download -i test.txt
--> Downloaded 294 vCard(s)

./carddav2fb convert -i test.txt convert.txt
--> Uploaded/refreshed 56 of 83 image file(s)
--> Converted 294 vCard(s)

./carddav2fb upload convert.txt
--> Successful uploaded new FRITZ!Box phonebook

./carddav2fb run -i
--> Downloaded 294 vCard(s)
--> Uploaded/refreshed 0 of 83 image file(s)
--> Converted 294 vCard(s)
--> Successful uploaded new FRITZ!Box phonebook

**Comment by SpamReceiver** [comment]
One possibly unrelated thing I have noticed. 
When I run `carddav2fb -i run`, the following message appears:
```
Detaching and uploading image(s)
294/294 [============================] 100%PHP Warning:  ftp_close(): SSL_read on shutdown: Connection reset by peer (104) in /mnt/data/var/carddav2fb/src/functions.php on line 289
 294/294 [============================] 100%
```

**Comment by andig** [comment]
That's an independent issue also noticed in #167.

Are you saying this didn't happen with previous versions?

**Comment by SpamReceiver** [comment]
I seldomly call the script from the command line, so I can't tell if the ftp_close() warning was happening earlier.
It was happening prior to this fix #172, though. I saw it when I was analysing why my photos didn't show up on the FritzFon.

**Pull request merged**
