### PR TITLE
Send Content-Type with xml request. #167

### PR DESCRIPTION
**Pull request by develth**
Fixes a HTTP 400 when Server wants the regarding Content-Type, too. Fixes https://github.com/andig/carddav2fb/issues/167.

### CODE REVIEW

**Comment by andig** [comment]
Are there any other requests where we would need to add the xml header?

**Comment by develth** [comment]
Nothing found until yet

**Comment by andig** [comment]
See https://travis-ci.org/andig/carddav2fb/jobs/634625477#L343, the indents are wrong.

**Comment by develth** [comment]
What should be 'correct'? Are you follow psr-2?

**Comment by andig** [comment]
We're using php-cs-fixer on travis:

    ./vendor/bin/php-cs-fixer fix --config=.php_cs.php -v --dry-run --diff --stop-on-violation

**Pull request merged**
