### PR TITLE
Alternativ: preserve quickdial and vanity attributes (Fixes #119)

### LINKED ISSUE #119: Enhancement: Preserve quickdial and vanity attributes from old phonebook
**TL;DR: I'll sent a PR for this enhancement**

The phone book with index "0" allows to specify quickdials and vanity strings for phone numbers
grafik

These attributes are proprietary to Fritzbox and not part of CardDav specification. When the CardDav editor allows custom fields (like e.g., OwnCloud/NextCloud), the carddav2fb script expects these attributes to be stored in the CardDav fields `X-FB-QUICKDIAL`and `X-FB-VANITY`.

But when you are forced to a CardDav editor that does not allow to specify own attributes, you can only set quickdial and vanity inside the Fritz!Box Web phonebook editor. In this case the quickdial and vanity strings get lost which each run of carddav2fb script.

Instead of overwriting the phone book blindly, we should rather
* Read in the old phonebook
* Extract specified quickdial and vanity string of contact numbers
* Restore these attributes in the new phone book if CardDavUID and phonenumber are identical
* Then upload the patched new phonebook to the FritzBox

### PR DESCRIPTION
**Pull request by BlackSenator**
Because the discussion about # 120 has fallen asleep, here's my alternative to stimulation:

What is different?
- download recent FRITZ!Box phonebook (equal to Wolfram´s solution) 
- save special attributes (less complex)
- write special attributes into CardDAV data (less complex)

### CODE REVIEW

**Comment by andig** [comment]
Das sieht schön kompakt aus! Bin auf die Kommentare von @derwok gespannt,

**Comment by derwok** [comment]
Sorry for beeing late to the party.
My last weekends were surpisingly blocked... so, I could not contribute as I wanted.
I understand, that @BlackSenator  pushed a new solution to wake me up... 
it worked.  :-)

Though looking very compact, I think the main reason for beeing compact is, that this new solution simply does not work... have you tried it?! 
May be I myself do overlook something here?! 
In case not...
I think it doesn work: Reason for this is: vanity & quickdial are attributes of a single phone number!
But a contact may have multiple phone numbers.
So, storing the attributes on "vCard UID level" ($key is the vCard UID) you lose the information which phonenumber they once belonged to...
On restoring the attributes you attach them to the contact? 
Not to the phone number? This should not work...
This was the reason why I combined my $key as cardUID+normalized phonenumber.

@andig : Please tell me, if you still like me to work on my PR and add unit tests... to my approach ASAP. Or you want to go ahead with @BlackSenator  approach. 
I'm also fine with this... But I think it needs some polishing...
I just want to avoid I code unit tests and then no merge is needed...

WOK.

**Comment by andig** [comment]
I‘m happy with either approach that works.

**Comment by BlackSenator** [comment]
It works, just as the previous solution works. Everything my solution suggestion is to write the data from the Fritzbox to the same place, as if the data come from the CardDAV server.
Everything else is as before: The assignment of quickdial/vanity to phone number via the "pref" feature: The "pref" erierte phone number of a contact is obviously the number that is also used as quickdial/vanity. Of course, the pref feature might indicate other numbers - but that would not make sense.

**Comment by derwok** [comment]
Hi @BlackSenator , thanks for explanation.
Let's keep up the discussion to find a good solution for our users and our code base.
:-)

While yesterday I only looked at code, today I gave it a "shot" - checked out your branch and tried with my local setup. Unfortunately it behaves like I expected: The vanity and quickdial attributes are not restored (saved) to the correct number where I entered them in the FB Web Editor. After a run of the script they always jump back to the very first number of the contact.
This is not as expected from user perspective, I fear.

Example: before script run:
grafik

After script run:
grafik

So, I wonder: where does the "pref" number come from?

**Comment by andig** [comment]
Makes sense. This pr is as good as the carddav solution, the other is actually offering more. Wondering if it wouldn‘t make sense to remove the x-carddav attributes at all?

**Comment by BlackSenator** [comment]
Okay, good point!
I have to admit that I put the "pref" in CardBook. Unfortunately there is on the iPhone in the contacts this option is not given, as I have just checked. Apple accepts and transports the feature - but does not let it edit.
My suggestion was just to keep the old solution (tested) and combines it with Wolfram’s.
As I said before: Andreas, it’s your choice!

**Comment by BlackSenator** [comment]
+ off topic +
@derwok
Your phonbook download is ways better than the SOAP version! SOAP access delivers only the content similar to the GUI, while the LUA version provides the full scope - even own XML nodes (like carddav_UID)
+ on topic +

**Comment by andig** [comment]
So- shall we remove the entire x-vanity attribute thing or is that still helpful?

**Comment by BlackSenator** [comment]
X-FB-* only makes sense for users which can set this field on tma carddav client and also have access to set pref.
Beside of this - I don’t think many users use quickdial and even less use vanity. For me it’s more to cover all phonebook fields with carddav2fb.

**Comment by andig** [comment]
Ok, then I'd propose to close this PR and get #120 merged as soon as it has tests as it provides better functionality.

**Comment by BlackSenator** [comment]
@derwok
To be honest, I think your implementation #120 is too complicated. Therefore, I have modified my alternative proposal so that it corresponds to your proposal for direct assignment of feature to number without "pref". In doing so, I was able to drastically cut down the previous function for assigning these features in converter.php.
I would be glad if you could examine this proposal critically.
The sun is shining - so now I´m out for garden work and digging in the ground :)

**Comment by derwok** [comment]
OK. I'll have a look at it this weekend...
If it works like expected without any "Config Hazzle" and with "FB Web Editor is Master" - then I will happily close my proposal...

**Comment by derwok** [comment]
Hey @BlackSenator 
I tried your alternative solution on my test environment. Unfortunately it still does not work (for me). It still did not preserve the quickdial & vanity attributes on the correct phone numbers. While your previous solution always attached QD/VA to the first number - your latest update now attaches the QD/VA to all(!) numbers of the affected contact.

Before script run:
grafik

After script run:
grafik

When I now press "Edit" in FB Web GUI on such a contact, the quickdial is changed to "01" and added to the first number - so basically this looks broken to me.

So, I decided to polish my PR #120 according to @andig suggestions, and added some unit tests for my new functions. Even phpstan is happy... - Ready for merge! 

So, - long story short - I would suggest we go with my proposal now and invest our precious time on some other cool features.  :-)  Anyway: Thanks for shaking me up again... and I really appreciate your energy you put in here! Peace.

**Comment by BlackSenator** [comment]
Your right,
I’ve now the same bad result. To be honest - tests befor show a correct behavior.
Mhmm, let’s check what happened.

**Comment by andig** [comment]
Closing this one in favor of @derwok - thats for all your support.

**Pull request closed without merging**
