### PR TITLE
Improve Image Upload. Fixes #75

### LINKED ISSUE #75: Image upload: some improvement ideas [PR exists]
I really like the image upload feature! Thanks!!
But I also see some improvement ideas.

**TL;DR: I will submit a pull request on this!**

1. Image upload was not stable on my FritzBox. Non-deterministically after 25 to 30 successful ftp uploads all(!) further images produces this error message:
```
ftp access denied for 68609498-7e94-40a7-a4a9-08da58ad55e5.jpg 
to /Sony-StorageMedia-01/FRITZ/fonpix
```
Assumption: server or client runs out of FTP connections? Don't know for sure. 
=> Suggestion: We should use one sticky FTP session for all image uploads.

2. The image handling with the functions `imagecreatefromstring` and `imagejpeg` uncompress the jpeg data and then recompress with lossy JPEG the image data. This costs time and results in less image quality. Users might assume that images have "same quality".
=> Suggestion: Just use the already existing JPEG data in `vcard->rawPhoto` and perform upload via fast in-memory stream

3. Current implementation always uploads ALL images. With lots of contact images with higher resolutions this might take quite some time and will stress FritzBox server unneccessary. As JPEG almost always changes +/- some bytes if content changes, we might simply rely upon file size.
=> Suggestion: Only upload if file size of photo changes. User can always force upload by removing all photos via FritzBox NAS.

4. As image upload of many high res images might take some time add a nice progress bar.

### PR DESCRIPTION
**Pull request by derwok**
* Keep single FTP session to increase stability
* No JPEG re-compression to keep image quality
* Only upload new/changed image files to increase performance
* Progressbar to increase usability
* Can handle "https://fritz.box" in config.php

Fixes #75

### CODE REVIEW

**Comment by andig** [comment]
Requires #73?

**Comment by andig** [comment]
Please check my review in #73

**Comment by derwok** [comment]
> Requires #73?

No, the two PRs are feature-wise indepentant. Nevertheless they target the same file.

**Comment by andig** [comment]
> No, the two PRs are feature-wise indepentant. Nevertheless they target the same file.

It still has all the ftp_ stuff inside- I guess you've branched from the feature branch instead of master, so it *is* dependent.

**Comment by derwok** [comment]
> > No, the two PRs are feature-wise indepentant. Nevertheless they target the same file.
> 
> It still has all the ftp_ stuff inside- I guess you've branched from the feature branch instead of master, so it _is_ dependent.

Hi,
I closed the master-branch-PR. And put both my contributions to separate branches now.

Regarding your question "ftp_*" stuff:
Yes, this was intentionally to fix the "#1" topic described in issue https://github.com/andig/carddav2fb/issues/75
My problem with the old implementation was: I had severe stability issues with FTP upload. Let me explain. My FritzBox is 7390 with latest firmware. The USB storage has lots of space. Nevertheless I could always only upload 25 to 30 files (non deterministic) then all further images got a "connection refused". 
As a temporay workaround I implemented "skip the first 25 uploads" - then the old implementation could successfully upload the remaining images.
So, my guess was: with `file_put_contents` there are either all FTP connections left open - OR - they are opened/closed so fast that either client (PHP) or server (my Fritzbox) have problems.

So, my idea here was to do the FTP open / login / chdir ONCE and then only loop over the "upload" call. Thats why I changed.

My observation with my new implementation is:
1.) It now - for the first time - works with my FritzBox in one rush to upload all > 100 images without any "connection refused" errors.
2.) The new upload code handles >100 files even faster than the old upload of 25 files - then upload always stopped.

So my vote for the new implementation.

**Comment by derwok** [comment]
The merging / conflict resolution should be simple, as changed code blocks do not overlap.

**Comment by andig** [comment]
I still don't like the array(0,0) returns. Would be better to return mixed in the docblock and false on error. Calling function should check for false and NOT use array indexes then. Also the symfony issue is still open.

Would you mind fixing the conflicts so I can merge? Just rebase on master.

**Comment by derwok** [comment]
I'll take care...
Thanks for the callback hint! (I'm not a PHP guy... sorry). But with the hint I could get it to work...
Also fixed the "return (0,0)" stuff...
Let's see if I can handle the rebase thing...  ;-) 
Stay tuned...

**Comment by andig** [comment]
Super, vielen Dank!

**Pull request merged**
