### PR TITLE
phoneTypes mapping added for work cell number (from nextcloud)

### PR DESCRIPTION
**Pull request by mrclschstr**
I added a `phoneTypes` mapping for work cell numbers in the `config.example.php` file. Within the nextcloud contacts app you can specify a work cell number, which is flagged as `CELL,WORK` in the vCard.

### CODE REVIEW

**Comment by blacksenator** [comment]
For two reasons, your suggestion makes no sense:
1. The config.example.php contains only sensible suggestions, each user can maintain their own conversions in its derived config.php.
2. Due to the fact that the FRITZ! Box assigns only one attribute per call number, the combination `WORK, CELL` of carddav2fb can only be resolved **to one of the two** values. The program logic therefore assigns the defined target value to the first matching find of the source data. With your suggestion, **all(!)** phone numbers marked with `CELL` would now be assigned the target value "mobile" because of the order. The following conversion `'CELL' => 'mobile',` will never be used.

@andig: PR can be closed

**Comment by mrclschstr** [comment]
You're wrong with your second point, but I get your first one. Closing the PR because the config.example.php is just an example.

**Comment by andig** [comment]
> Closing the PR because the config.example.php is just an example.

@mrclschstr any improvement of the suggested default configuration is welcome! If point 1 doesn't apply according to your tests we could still merge this.

**Comment by mrclschstr** [comment]
I'll double check my tests and get back to you!

**Comment by blacksenator** [comment]
I  just checked my (wrong?) point 2 - and see me confirmed:
I created a telephone book as a test with the following entry:
grafik

After download I added the contact like this:
```
<?xml version="1.0" encoding="utf-8"?>
<phonebooks>
    <phonebook owner="2" name="Test">
        <contact>
            <category>0</category>
            <person>
                <realName>Dummy</realName>
            </person>
            <telephony nid="3">
                <number type="home" prio="1" id="0">05605367373</number>
                <number type="mobile" id="1">015137567893</number>
                <number type="work" id="2">056056780227</number>
                <number type="mobile,work" id="3">017798765432</number>
            </telephony>
            <services />
            <setup />
            <features doorphone="0" />
            <mod_time>1561056592</mod_time>
            <uniqueid>2198997</uniqueid>
        </contact>
    </phonebook>
</phonebooks>
```
and after upload to Fritz!Box the result is like expected:

grafik

**The FRITZ!Box can not interpret more than one type attribute!**

But the most terrific finding is: **you can not delete the entry "sonstige" from the GUI!** It still resists in the contact - even if you think you have deleted it.

I stick to it - the suggestion makes no sense and as an example in the `example.config.php` it leads rather to the confusion of users

**Comment by andig** [comment]
If we create invalid fb entries that should be handled during conversion. The rule- converting to cell- looks innovent enough.

**Comment by andig** [comment]
I think your test is flawed- the mapping if from carddav to fb, not the other way around?

**Comment by blacksenator** [comment]
I used the test to simulate what the transcoding, or <number> line would look like, to take into account the mapping suggested by mrclschstr. But you can take the counter proof ...

**Comment by mrclschstr** [comment]
As far as I understood the `phoneTypes` setting, it's used to map the phone types of CardDAV to a known format of the FritzBox. When I export my contacts from my nextcloud I get results like this for work related mobile numbers: `TEL;TYPE=CELL,WORK:+49XXXXXXXXXXXXX`.

When I add the code of my PR to `phoneTypes`, these mobile numbers will be shown as "work" in my FritzBox. Did I get that whole concept wrong? Is it just a lucky coincidence that it works for me?

The ordering of that mapping might be debatable.

**Comment by blacksenator** [comment]
As I have tried to explain: The FRITZ!Box knows (shows) only one type attributes per phone number. Therefore, only one source value can be taken into account during mapping - either `CELL` or `WORK`. It can only be assigned to one - well then `mobile` or `work` - not both.

The conversion routine therefore takes the first matching source value and assigns to it the target value defined in the mapping. In your case `CELL`. If you would prefer to have `WORK` for this special number, then the order in the vCard must be changed in the Nextcloud: `TEL; TYPE = WORK, CELL: + 49XXXXXXXXXXXXX` (if that works).

To adapt the mapping or the mappingroutine for this would be an intervention which then would affect all other numbers.

I do not see any other possibility - except to ask AVM (Entwicklungssupport@avm.de) to extend their limit of the four target values (`home`, `work`, `mobile`, `fax_work`) to the GUI designations (`geschäftl.`, `privat`, `mobil` or `FAX`). If another value is passed, the GUI will show `sonstige`

**Comment by blacksenator** [comment]
If I understand you correctly, than in the Fritz! Box actually should be `mobil` appear, but `geschäftl.` is displayed.
Okay, that would be a bug! Because first the `CELL` value should be found, and would have to be converted accordingly to `mobile`.
I have to look at that. You can also look into the coding yourself: https://github.com/andig/carddav2fb/blob/a9576b1e67ae79a1b9b55fd4d68954acc047b1dc/src/FritzBox/Converter.php#L149
I think it's on line 161 (`if (stripos($numberType, $phoneType) !== false) {`). @andig: I check in parallel, whether the problem does not resolve itself with the [vcardlib](https://github.com/andig/carddav2fb/pull/145), since it no longer finds your JSON structure use, which groups the phone numbers by type.

**Comment by andig** [comment]
Ich machs mal auf Deutsch. Die Konvertierung passiert in https://github.com/andig/carddav2fb/blob/master/src/FritzBox/Converter.php#L160.

Da wird von CardDAV auf exakt einen Telefontyp im Ziel gemappt. `stripos` bedeutet, dass der Nummerntyp des CardDAV Kontaktes in der Mappingliste gesucht wird. Also: falls `CELL,WORK` im Kontakt, wird im Ziel `work` ausgewählt.

Für mich sieht das alles pausibel aus. @blacksenator wo ist jetzt das konkrete Problem?

**Comment by andig** [comment]
@mrclschstr konntest Du es nochmal testen?

**Comment by mrclschstr** [comment]
Sorry für die späte Rückmeldung!

> @mrclschstr das sollte allerdings auch ohne Deine Änderung funktionieren, da dann eben `WORK` als Substring gefunden wird und ebenfalls auf `work` gemappt.

Das ist soweit korrekt. Ich kann leider nicht mehr nachvollziehen, warum die Zuordnung ohne meine Anpassung initial nicht geklappt hat. PR kann geschlossen und verworfen werden.

**Comment by andig** [comment]
> Das ist soweit korrekt. Ich kann leider nicht mehr nachvollziehen, warum die Zuordnung ohne meine Anpassung initial nicht geklappt hat. PR kann geschlossen und verworfen werden.

Kein Problem- dann hat es sich doch aber gelohnt das nochmal in Ruhe zu diskutieren. Danke für Dein Interesse und die Unterstützung!

**Pull request closed without merging**
