### PR TITLE
Use REPORT method

### LINKED ISSUE #50: CardDAV sends empty reply to GET resource request
Beim Download von einer CardDAV Ressource (v3.0) werden diese nicht korrekt geparst bzw. heruntergeladen:
```
root@server0:/var/www/carddav2fb-mid# php carddav2fb.php run
Downloading vCard(s) from account xxx
 1873 [============================]
Downloaded 1873 vCard(s)
Parsing vcards

In Parser.php line 89:
                          
  [OutOfBoundsException]  
                          

run [-i|--image] [-c|--config CONFIG]
```

### PR DESCRIPTION
**Pull request by andig**
Fix #50

/cc @blacksenator @mokkin

### CODE REVIEW

**Comment by andig** [comment]
Double-checked and is working with iCloud for me

**Comment by mokkin** [comment]
That's strange: with the patch applied it doesn't download any card.
Not from my nextcloud and not from the account I sent you the credentials.

**Comment by andig** [comment]
Setz mal bitte `http => debug = true` und schick mir per pm die Ausgabe von

    ./carddav2fb download

Bei mir ging das tatsächlich wunderbar.

**Comment by mokkin** [comment]
siehe PM

**Comment by mokkin** [comment]
That's cool!
With your last change it's working perfectly and like 100 times faster!
:+1: for pushing the pull request

**Comment by mokkin** [comment]
Just one addition:
If there is a really empty addressbook between the ones with contacts, the download fails.
That's not a big problem, because you simply can uncomment the one, but maybe this can be skipped.

```
php carddav2fb.php run
Downloading vCard(s) from account user
  401 [============================]
Downloaded 401 vCard(s)
Downloading vCard(s) from account user
   56 [============================]
Downloaded 858 vCard(s)
Downloading vCard(s) from account user
   81 [============================]
Downloaded 1396 vCard(s)
Downloading vCard(s) from account user
  465 [============================]
Downloaded 2399 vCard(s)
Downloading vCard(s) from account user
   44 [============================]
Downloaded 3446 vCard(s)
Downloading vCard(s) from account user
  107 [============================]
Downloaded 4600 vCard(s)
Downloading vCard(s) from account user
  124 [============================]
Downloaded 5878 vCard(s)
Downloading vCard(s) from account user
  349 [============================]
Downloaded 7505 vCard(s)
Downloading vCard(s) from account user
    3 [============================]
Downloaded 9135 vCard(s)
Downloading vCard(s) from account user
  167 [============================]
Downloaded 10932 vCard(s)
Downloading vCard(s) from account user
   14 [============================]
Downloaded 12743 vCard(s)
Downloading vCard(s) from account user
   35 [============================]
Downloaded 14589 vCard(s)
Downloading vCard(s) from account user
    1 [============================]
Downloaded 16436 vCard(s)
Downloading vCard(s) from account user
    5 [============================]
Downloaded 18288 vCard(s)
Downloading vCard(s) from account user
   14 [============================]
Downloaded 20154 vCard(s)
Downloading vCard(s) from account user
   31 [============================]
Downloaded 22051 vCard(s)
Downloading vCard(s) from account user
    3 [============================]
Downloaded 23951 vCard(s)
Downloading vCard(s) from account user
    0 [>---------------------------]* Hostname carddav.example.com was found in DNS cache
*   Trying 13.95.212.214...
* TCP_NODELAY set
* Connected to carddav.example.com (13.95.212.214) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=carddav.example.com
*  start date: Feb 19 18:33:45 2019 GMT
*  expire date: May 20 18:33:45 2019 GMT
*  subjectAltName: host "carddav.example.com" matched cert's "carddav.example.com"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> REPORT /addressbooks/xxxxxx/yyyyyy/ HTTP/1.1
Host: carddav.example.com
Depth: 1
User-Agent: GuzzleHttp/6.3.3 curl/7.52.1 PHP/7.2.15-1+0~20190209065123.16+stretch~1.gbp3ad8c0
Authorization: Basic bWhheWJhY2g6VGVzdDEyMzQ1OA==
Content-Length: 239

* upload completely sent off: 239 out of 239 bytes
< HTTP/1.1 404 Not Found
< Content-Length: 300
< Content-Type: application/xml; charset=utf-8
< Date: Tue, 26 Mar 2019 21:19:40 GMT
< Server: Apache/2.4.25 (Debian)
< Vary: Accept-Encoding
< X-Powered-By: PHP/7.2.4
< X-Sabre-Version: 3.2.2
< 
* Curl_http_done: called premature == 0
* Connection #0 to host carddav.example.com left intact

In RequestException.php line 113:
                                                                                                                                           
  Client error: `REPORT https://carddav.example.com/addressbooks/xxxxxx/yyyyyy/` resulted in a `404 Not Found` response:  
  <?xml version="1.0" encoding="utf-8"?>                                                                                                   
  <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">                                                                                
    <s:sabredav-version>3 (truncated...)                                                                                                   
                                                                                                                                           

run [-i|--image] [-c|--config CONFIG]
```
(without the empty addressbook the down- and upload is fine)

**Comment by andig** [comment]
Kinda ugly because we cannot be sure if really the URL is not found or the server sends an empty response. Anyway it's ignored now and logged.

**Comment by mokkin** [comment]
:+1: works too:
```
Downloaded 1900 vCard(s)
Downloading vCard(s) from account user
    0 [>---------------------------]Ignoring empty response from carddav REPORT request
    0 [>---------------------------]
Downloaded 1900 vCard(s)

```

**Comment by BlackSenator** [comment]
Runs like hell! 👍

**Pull request merged**
